### ISSUE TITLE
Request::is returns false incorrectly

### ISSUE THREAD

**Issue by TomWright** [JordanDoyle/Animus#3]
I just did the following as a test...
The following code was executed on `http://animus.mydomain.co.uk/tom/test`

    var_dump(Request::is('tom/test'));

The output is `bool(false)`

This must be why I can't get normal routes working! Controller routes work but this happens with get/post.

**Comment by JordanDoyle** [comment]
What does `Request::path()` return?

**Comment by JordanDoyle** [comment]
Should be fixed by de02a9089d45622f2181c751ec5e32a0b7869e8f, can you confirm?

**Comment by TomWright** [comment]
I will check in a couple of hours

**Comment by TomWright** [comment]
I can confirm that the following now works.

Route:

    Router::get('tom/test', 'App\Controller\TomController@test');

Controller:

    class TomController extends Controller {

	public function test()
	{
		return "Found me!";
	}

}
